#!/usr/bin/env python
#
# Copyright (c) 2018 Martin Pieuchot
# Copyright (c) 2018 Samuel Thibault <sthibault@hypra.fr>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Take LibreOffice (glade) .ui files and check for non accessible widgets

from __future__ import print_function

import os
import sys
import getopt
try:
    import lxml.etree as ET
    lxml = True
except ImportError:
    if sys.version_info < (2,7):
        print("gla11y needs lxml or python >= 2.7")
        exit()
    import xml.etree.ElementTree as ET
    lxml = False


widgets_ignored = [
    'GtkFrame',
    'GtkWindow',
    'GtkScrolledWindow',
    'GtkDialog',
    'GtkMessageDialog',
    'GtkNotebook',

    # Invisible actions
    'GtkAlignment',
    'GtkAdjustment',
    'GtkBox',
    'GtkVBox',
    'GtkHBox',
    'GtkButtonBox',
    'GtkGrid',
    'GtkSizeGroup',
    'GtkSeparator',
    'GtkExpander',
    'GtkActionGroup',
    'GtkViewport',
    'GtkPaned',
    'GtkCellRendererText',

    'sfxlo-PriorityHBox',
    'sfxlo-PriorityMergedHBox',
    'sfxlo-ContextVBox',

    'GtkScrollbar',
    'GtkListBox',
    'GtkStatusbar',

    # Storage objects
    'GtkListStore',
    'GtkTextBuffer',
    'GtkTreeSelection',

    'svtlo-ValueSet',

    # Menus are fine
    'GtkMenu',
    'GtkMenuItem',
    'GtkRadioMenuItem',
    'GtkSeparatorMenuItem',
    'GtkCheckMenuItem',

    # Toolbars are fine
    # FIXME: err, they need an action name
    'GtkToolbar',
    'GtkSeparatorToolItem',
    'GtkToggleToolButton',
    'GtkRadioToolButton',
    'GtkMenuToolButton',
    'GtkToolButton',
    'GtkToolItem',

    'sfxlo-NotebookbarToolBox',
    'sfxlo-SidebarToolBox',
    'svtlo-ManagedMenuButton',
    'vcllo-SmallButton',
    'sfxlo-NotebookbarTabControl',
    'sfxlo-DropdownBox',
    'sfxlo-OptionalBox',

    'vcllo-PrintPreviewWindow',
    'cuilo-SvxNumberPreview',
    'cuilo-BackgroundPreview',

    'AtkObject',
]

# To include for LO for sure:
# svxcorelo-SvxColorListBox
# svxcorelo-SvxLanguageBox comme ComboBox
# foruilo-RefButton
# sfxlo-SvxCharView
# foruilo-RefEdit
# svxcorelo-PaperSizeListBox comme combobox
# mettre tous les svxcorelo?

# svtlo-SvSimpleTableContainer ?

# svxcorelo-SvxCheckListBox ?
# svtlo-SvTreeListBox ?

progname = os.path.basename(sys.argv[0])
suppressions = {}
ids = {}
gen_suppr = None
gen_supprfile = None
suppr_prefix = ""
outfile = None
pflag = False
Werror = False
Wnone = False
errors = 0
errexists = 0
warnings = 0
warnexists = 0

def elm_parent(root, elm):
    """
    Return the parent of the element.
    """
    if lxml:
        return elm.getparent()
    else:
        def find_parent(cur, elm):
            for o in cur:
                if o == elm:
                    return cur
                parent = find_parent(o, elm)
                if parent is not None:
                    return parent
            return None
        return find_parent(root, elm)

def elm_labelled_parent(root, elm):
    """
    Return the first labelled parent of the element, which can thus be used as
    the root of widgets with common labelled context
    """

    def is_labelled_parent(elm):
        """
        Return whether this element is a labelled parent
        """
        klass = elm.attrib.get('class')
        if klass == 'GtkDialog':
            return True
        if klass == 'GtkFrame' or klass == 'GtkNotebook':
            children = elm.findall("child[@type='tab']") + elm.findall("child[@type='label']") 
            if len(children) >= 1:
                return True
        return False

    if lxml:
        def find_labelled_parent(elm):
            if is_labelled_parent(elm):
                return elm
            parent = elm.getparent()
            if parent is None:
                return None
            return find_labelled_parent(parent)
        parent = elm.getparent()
        if parent is None:
            return None
        return find_labelled_parent(elm.getparent())
    else:
        def find_labelled_parent(cur, elm):
            if cur == elm:
                # the target element is over there
                return True
            for o in cur:
                parent = find_labelled_parent(o, elm)
                if parent == True:
                    # target element is over there, check ourself
                    if is_labelled_parent(cur):
                        # yes, and we are the first ancestor of the target element
                        return cur
                    else:
                        # no, but target element is over there.
                        return True
                if parent != None:
                    # the first ancestor of the target element was over there
                    return parent
            return None
        parent = find_labelled_parent(root, elm)
        if parent == True:
            parent = None
        return parent

def orphaned_label(filename, tree, root, obj):
    """
    Check whether this label has no accessibility relation
    """
    label_for = obj.findall("accessibility/relation[@type='label-for']")
    check_rels(filename, tree, root, obj, label_for)

    # Case 0: A 'GtkLabel' must contain one or more "label-for"
    # pointing to existing elements or...
    if len(label_for) > 0:
        return False

    no_label_for = obj.findall("accessibility/relation[@type='no-label-for']")
    if len(no_label_for) > 0:
        return False

    # ...a single "mnemonic_widget"
    properties = obj.findall("property[@name='mnemonic_widget']")
    check_props(filename, tree, root, obj, properties)
    if len(properties) > 1:
        # FIXME: shouldn't emit error ourself...
        err(filename, tree, obj, "multiple-mnemonic", "has multiple mnemonic_widgets properties"
            "%s" % elms_lines(properties))
        return False
    if len(properties) == 1:
        return False

    parent = elm_parent(root, obj)
    if parent is not None:
        childtype = parent.attrib.get('type')
        if parent.tag == 'child' and childtype == 'label' \
                                  or childtype == 'tab':
            # This is a frame or a notebook label
            return False
    return True

def orphaned_labels(filename, tree, root, elm):
    """
    Check whether from root there exists a label with no accessibility relation
    """
    l = []
    def look(obj):
        if obj.attrib.get('class') == 'GtkLabel' and \
            orphaned_label(filename, tree, root, obj):
            l.append(obj)
        for o in obj:
            look(o)
    look(elm)
    return l

def step_elm(elm):
    """
    Return the XML class path step corresponding to elm.
    This can be empty if the elm does not have any class or id.
    """
    step = elm.attrib.get('class')
    if step is None:
        step = ""
    oid = elm.attrib.get('id')
    if oid is not None:
        oid = oid.encode('ascii','ignore').decode('ascii')
        step += "[@id='%s']" % oid
    if len(step) > 0:
        step += '/'
    return step

def find_elm(root, elm):
    """
    Return the XML class path of the element from the given root.
    This is the slow version used when getparent is not available.
    """
    if root == elm:
        return ""
    for o in root:
        path = find_elm(o, elm)
        if path is not None:
            step = step_elm(o)
            return step + path
    return None

def errpath(filename, tree, elm):
    """
    Return the XML class path of the element
    """
    if elm is None:
        return ""
    path = ""
    if 'class' in elm.attrib:
        path += elm.attrib['class']
    oid = elm.attrib.get('id')
    if oid is not None:
        oid = oid.encode('ascii','ignore').decode('ascii')
        path += "[@id='%s']" % oid
    if lxml:
        elm = elm.getparent()
        while elm is not None:
            step = step_elm(elm)
            path = step + path
            elm = elm.getparent()
    else:
        path = find_elm(tree.getroot(), elm)[:-1]
    path = filename + ':' + path
    return path

def elm_prefix(filename, elm):
    """
    Return the display prefix of the element
    """
    if elm == None or not lxml:
        return "%s:" % filename
    else:
        return "%s:%u" % (filename, elm.sourceline)

def elm_name(elm):
    """
    Return a display name of the element
    """
    if elm is not None:
        name = ""
        if 'class' in elm.attrib:
            name = "'%s' " % elm.attrib['class']
        if 'id' in elm.attrib:
            id = elm.attrib['id'].encode('ascii','ignore').decode('ascii')
            name += "'%s' " % id
        if not name:
            name = elm.tag
            if lxml:
                name += " line " + str(elm.sourceline)
        return name
    return ""

def elm_suppr(filename, tree, elm, msgtype):
    """
    Return the prefix to be displayed to the user and the suppression line for
    the warning type "msgtype" for element "elm"
    """
    global gen_suppr, gen_supprfile, suppr_prefix, pflag

    if suppressions or gen_suppr is not None or pflag:
        prefix = errpath(filename, tree, elm)
        if prefix[0:len(suppr_prefix)] == suppr_prefix:
            prefix = prefix[len(suppr_prefix):]

    if suppressions or gen_suppr is not None:
        suppr = '%s %s' % (prefix, msgtype)

        if gen_suppr is not None and msgtype is not None:
            if gen_supprfile is None:
                gen_supprfile = open(gen_suppr, 'w')
            print(suppr, file=gen_supprfile)
    else:
        suppr = None

    if not pflag:
        # Use user-friendly line numbers
        prefix = elm_prefix(filename, elm)
        if prefix[0:len(suppr_prefix)] == suppr_prefix:
            prefix = prefix[len(suppr_prefix):]

    return (prefix, suppr)

def err(filename, tree, elm, msgtype, msg):
    """
    Emit an error for an element
    """
    global errors, errexists

    (prefix, suppr) = elm_suppr(filename, tree, elm, msgtype)

    if suppr in suppressions:
        # Suppressed
        errexists += 1
        return

    errors += 1
    msg = "%s ERROR: %s%s" % (prefix, elm_name(elm), msg)
    print(msg)
    if outfile is not None:
        print(msg, file=outfile)


def warn(filename, tree, elm, msgtype, msg):
    """
    Emit a warning for an element
    """
    global Werror, Wnone, errors, errexists, warnings, warnexists

    if Wnone:
        return

    (prefix, suppr) = elm_suppr(filename, tree, elm, msgtype)
    if suppr in suppressions:
        # Suppressed
        if Werror:
            errexists += 1
        else:
            warnexists += 1
        return

    if Werror:
        errors += 1
    else:
        warnings += 1

    msg = "%s WARNING: %s%s" % (prefix, elm_name(elm), msg)
    print(msg)
    if outfile is not None:
        print(msg, file=outfile)


def check_props(filename, tree, root, elm, props):
    """
    Check the given list of relation properties
    """
    for prop in props:
        if prop.text not in ids:
            err(filename, tree, elm, "undeclared-target", "uses undeclared target '%s'" % prop.text)

def check_rels(filename, tree, root, elm, rels):
    """
    Check the given list of relations
    """
    for rel in rels:
        target = rel.attrib['target']
        if target not in ids:
            err(filename, tree, elm, "undeclared-target", "uses undeclared target '%s'" % target)

def elm_line(elm):
    """
    Return the line for the given element.
    """
    if lxml:
        return " line " + str(elm.sourceline)
    else:
        return ""

def elms_lines(elms):
    """
    Return the list of lines for the given elements.
    """
    if lxml:
        return " lines " + ', '.join([str(l.sourceline) for l in elms])
    else:
        return ""

def check_a11y_relation(filename, tree):
    """
    Emit an error message if any of the 'object' elements of the XML
    document represented by `root' doesn't comply with Accessibility
    rules.
    """
    global widgets_ignored, ids
    root = tree.getroot()

    ids = {}

    for obj in root.iter('object'):
        oid = obj.attrib.get('id')
        if oid is not None:
            if oid in ids:
                o = ids[oid]
                warn(filename, tree, obj, "duplicate-id", "has the same id as " + elm_name(o) + elm_line(o))
            else:
                ids[oid] = obj

    for obj in root.iter('object'):
        if obj.attrib['class'] in widgets_ignored:
            continue

        requires_label = False

        labelled_by = obj.findall("accessibility/relation[@type='labelled-by']")
        check_rels(filename, tree, root, obj, labelled_by)

        member_of = obj.findall("accessibility/relation[@type='member-of']")
        check_rels(filename, tree, root, obj, member_of)

        klass = obj.attrib.get('class')

        if klass == 'GtkLabel':
            if orphaned_label(filename, tree, root, obj):
                label_root = elm_labelled_parent(root, obj)
                if label_root is None:
                    label_root = root
                context = elm_name(label_root)
                if context:
                    context = " within " + context
                warn(filename, tree, obj, "no-label-for", "does not specify what it labels" + context)
            continue

        # Not a label

        ## Should not have label-for
        #label_for = obj.findall("accessibility/relation[@type='label-for']")
        #if len(label_for) > 0:
        #    # TODO: should it be supported by Orca, or just reversed?
        #    err(filename, tree, obj, "label-for", "has label-for relation, but is not a label")

        # Case 1: has a <child internal-child="accessible"> sub-element
        children = obj.findall("child[@internal-child='accessible']")
        if children:
            if len(children) > 1:
                err(filename, tree, obj, "multiple-accessible", "has multiple <child internal-child='accessible'>"
                    "%s" % elms_lines(children))
            continue

        # Case 2: has an <accessibility> sub-element with a "labelled-by"
        # <relation> pointing to an existing element.
        if len(labelled_by) > 0:
            continue

        # TODO: check with orca
        ## has an <accessibility> sub-element with a "member-of"
        ## <relation> pointing to an existing element.
        #if len(member_of) > 0:
        #    continue

        # Case 3/4: has an ID...
        oid = obj.attrib.get('id')
        if oid is not None:
            # ...referenced by a single "label-for" <relation>
            rels = root.iterfind(".//relation[@target='%s']" % oid)
            labelfor = [r for r in rels if r.attrib.get('type') == 'label-for']
            if len(labelfor) == 1:
                continue
            if len(labelfor) > 1:
                err(filename, tree, obj, "multiple-label-for", "is referenced by multiple <relation type='label-for' target='%s'>"
                    "%s" % (oid, elms_lines(labelfor)))
                continue

            # ...referenced by a single "mnemonic_widget"
            props = root.iterfind(".//property[@name='mnemonic_widget']")
            props = [p for p in props if p.text == oid]
            if len(props) == 1:
                continue
            if len(props) > 1:
                warn(filename, tree, obj, "multiple-mnemonic", "is referenced by multiple mnemonic_widget"
                    "%s" % elms_lines(props))
                continue

        tooltips = obj.findall("property[@name='tooltip_text']")
        if len(tooltips) > 1:
            err(filename, tree, obj, "multiple-tooltip", "has multiple tooltip_text properties")
        if len(tooltips) == 1:
            # Has a <property name="tooltip_text">
            continue

        placeholders = obj.findall("property[@name='placeholder_text']")
        if len(placeholders) > 1:
            err(filename, tree, obj, "multiple-placeholder", "has multiple placeholder_text properties")
        if len(placeholders) == 1:
            # Has a <property name="placeholder_text">
            continue

        # GtkButtons usually don't need an external label, their own is enough.
        if klass == "GtkButton" or klass == "GtkToolButton" :

            labels = obj.findall("property[@name='label']")
            if len(labels) > 1:
                err(filename, tree, obj, "multiple-label", "has multiple label properties")
            if len(labels) == 1:
                # Has a <property name="label">
                continue

            actions = obj.findall("property[@name='action_name']")
            if len(actions) > 1:
                err(filename, tree, obj, "multiple-action_name", "has multiple action_name properties")
            if len(actions) == 1:
                # Has a <property name="action_name">
                continue

            # no label for a button, warn
            warn(filename, tree, obj, "button-no-label", "does not have its own label");
            continue

        if klass == "GtkImage":
            uses = tree.iterfind("//object/property[@name='image']")
            uses = [u for u in uses if u.text == oid]
            if len(uses) > 0:
                # This image is just used by another element, don't warn
                # about the image itself, we probably want the warning on
                # the element instead.
                continue

        parent = elm_parent(root, obj)
        if parent is not None:
            if klass == 'GtkEntry' and parent.tag == 'child' and \
                parent.attrib.get('internal-child') == "entry":
                # This is an internal entry of another widget. That one will
                # need relations etc.
                continue

        # So, no label
        if klass == 'GtkEntry' or klass == 'GtkScale' or klass == 'GtkSpinButton':
            requires_label = True

        label_root = elm_labelled_parent(root, obj)
        if label_root is None:
            # No labelled root, look for labels from the root
            label_root = root
        # TODO: or a widget with several mnemonics or label-for

        if len(orphaned_labels(filename, tree, root, label_root)) == 0:
            # But no orphaned label either, so probably the labelled parent
            # provides enough context.
            if requires_label:
                # These always need a label.
                warn(filename, tree, obj, "no-labelled-by", "has no accessibility label")
            continue

        context = elm_name(label_root)
        if context:
            context = " within " + context
        warn(filename, tree, obj, "no-labelled-by", "has no accessibility label while there are orphaned labels" + context)
        continue

def usage():
    print("%s [-W error|none] [-p] [-g SUPPR_FILE] [-s SUPPR_FILE] [-i WIDGET1,WIDGET2[,...]] [-o LOG_FILE] [file ...]" % progname,
          file=sys.stderr)
    print("  -p print XML class path instead of line number");
    print("  -g Generate suppression file SUPPR_FILE");
    print("  -s Suppress warnings given by file SUPPR_FILE");
    print("  -i Ignore warnings for widgets of a given class");
    print("  -o Also prints errors and warnings to given file");
    sys.exit(2)


def main():
    global pflag, Werror, Wnone, gen_suppr, gen_supprfile, suppressions, suppr_prefix, errors, widgets_ignored, outfile

    try:
        opts, args = getopt.getopt(sys.argv[1:], "W:piIg:s:P:o:L:")
    except getopt.GetoptError:
        usage()

    suppr = None
    out = None
    filelist = None
    ignore = False
    widgets = []

    for o, a in opts:
        if o == "-W":
            if a == "error":
                Werror = True
            elif a == "none":
                Wnone = True
        elif o == "-p":
            pflag = True
        elif o == "-i":
            widgets = a.split(',')
        elif o == "-I":
            ignore = True
        elif o == "-g":
            gen_suppr = a
        elif o == "-s":
            suppr = a
        elif o == "-P":
            suppr_prefix = a
        elif o == "-o":
            out = a
        elif o == "-L":
            filelist = a

    if ignore and widgets:
        usage()

    if ignore:
        widgets_ignored = []
    elif widgets:
        widgets_ignored.extend(widgets)

    # Read suppression file before overwriting it
    if suppr is not None:
        try:
            supprfile = open(suppr, 'r')
            for line in supprfile.readlines():
                prefix = line.rstrip()
                suppressions[prefix] = True
            supprfile.close()
        except IOError:
            pass

    if out is not None:
        outfile = open(out, 'w')

    if filelist is not None:
        try:
            filelistfile = open(filelist, 'r')
            for line in filelistfile.readlines():
                line = line.strip()
                if line:
                    args += line.split(' ')
            filelistfile.close()
        except IOError:
            err(filelist, None, None, "unable to read file list file")

    for filename in args:
        try:
            tree = ET.parse(filename)
        except ET.ParseError:
            err(filename, None, None, "parse", "malformatted xml file")
            continue
        except IOError:
            err(filename, None, None, None, "unable to read file")
            continue

        try:
            check_a11y_relation(filename, tree)
        except Exception as error:
            import traceback
            traceback.print_exc()
            err(filename, None, None, "parse", "error parsing file")

    if errors > 0 or errexists > 0:
        estr = "%s new error%s" % (errors, 's' if errors > 1 else '')
        if errexists > 0:
            estr += " (%s suppressed by %s)" % (errexists, suppr)
        print(estr)

    if warnings > 0 or warnexists > 0:
        wstr = "%s new warning%s" % (warnings,
                                           's' if warnings > 1 else '')
        if warnexists > 0:
            wstr += " (%s suppressed by %s)" % (warnexists, suppr)
        print(wstr)

    if gen_supprfile is not None:
        gen_supprfile.close()
    if outfile is not None:
        outfile.close()
    if errors > 0 and gen_suppr is None:
        sys.exit(1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass

# vim: set shiftwidth=4 softtabstop=4 expandtab:
